name: Build Airbeats

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Inject Secrets into .env
      run: |
        echo "STATS_API_KEY=${{ secrets.STATS_API_KEY }}" > .env
        echo "STATS_BASE_URL=https://database.airbeats.app" >> .env
        echo "GLOBAL_STATS_FILE=airbeats/global_stats.json" >> .env
        echo "FCM_STATS_FILE=airbeats/fcm.json" >> .env
        echo "MAX_GLOBAL_USERS=10000000" >> .env
        echo "PROJECT_ID=${{ secrets.PROJECT_ID }}" >> .env
        echo "AUTH_API_BASE_URL=https://auth.airbeats.app" >> .env


    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build Python backend (Windows)
      if: matrix.os == 'windows-latest'
      run: pyinstaller --name server --onedir --noconsole --add-data "templates;templates" --add-data "static;static" --collect-data ytmusicapi -y app.py

    - name: Build Python backend (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        pyinstaller --name server --onedir --noconsole --add-data "templates:templates" --add-data "static:static" --collect-data ytmusicapi -y app.py
        mv dist/server/server dist/server/server.exe

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install Node dependencies
      working-directory: ./electron-app
      run: npm install

    - name: Build Electron app (Windows)
      if: matrix.os == 'windows-latest'
      working-directory: ./electron-app
      run: npx electron-builder --win --publish never

    - name: Build Electron app (macOS)
      if: matrix.os == 'macos-latest'
      working-directory: ./electron-app
      run: npx electron-builder --mac --publish never

    - name: Install Snapcraft (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: sudo snap install snapcraft --classic

    - name: Build Electron app (Linux)
      if: matrix.os == 'ubuntu-latest'
      working-directory: ./electron-app
      run: npx electron-builder --linux --publish never

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: airbeats-${{ matrix.os }}
        path: |
          electron-app/dist/*.exe
          electron-app/dist/*.dmg
          electron-app/dist/*.AppImage
          electron-app/dist/*.deb
          electron-app/dist/*.snap

    - name: Publish to GitHub Releases
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          electron-app/dist/*.exe
          electron-app/dist/*.dmg
          electron-app/dist/*.AppImage
          electron-app/dist/*.deb
          electron-app/dist/*.snap






